title: "Daniel S치nchez Ordo침ez"
description: Academic Website of Daniel S치nchez Ordo침ez  
  [游늯 CV](/assets/cv.pdf) | [游닎 Email](mailto:your@email.com) | [游댕 LinkedIn](https://linkedin.com/in/YOUR-LINKEDIN)
theme: jekyll-theme-minimal
logo: /assets/profile.jpg
show_downloads: True
