title: "Daniel S치nchez Ordo침ez"
description: >
  Academic Website of Daniel S치nchez Ordo침ez  
  <a href="/assets/cv.pdf">游늯 CV</a> |
  <a href="mailto:d.sanchez.ordonez@psemail.eu">游닎 Email</a> 
logo: /assets/profile.jpeg
theme: jekyll-theme-minimal
show_downloads: false
github:
  is_project_page: false
