title: "Daniel S치nchez Ordo침ez"
description: >
  Academic Website of Daniel S치nchez Ordo침ez  
  <a href="/assets/cv.pdf">游늯 CV</a> |
  <a href="mailto:your@email.com">游닎 Email</a> |
  <a href="https://linkedin.com/in/YOUR-LINKEDIN">游댕 LinkedIn</a>
logo: /assets/profile.jpeg
theme: jekyll-theme-minimal
show_downloads: false
