title: "Daniel S치nchez Ordo침ez"
description: "Academic Website of Daniel S치nchez Ordo침ez"
theme: jekyll-theme-minimal
logo: /assets/img/profile.jpg   # you can add a picture later
show_downloads: false
