title: "Daniel Sánchez Ordoñez"
description: >
  PhD Candidate, Paris School of Economics
  <a href="/assets/cv.pdf">📄 CV</a> |
  <a href="mailto:d.sanchez.ordonez@psemail.eu">📧 Email</a> 
  >
  hdfghdfgh
logo: /assets/profile.jpeg
theme: jekyll-theme-minimal
show_downloads: false
