title: "Daniel Sánchez Ordóñez"
description: >
  PhD Candidate, Paris School of Economics<br>
  <a href="https://www.dropbox.com/scl/fi/dqsr70ngonbbebqgcvg1d/cv.pdf?rlkey=wg4ig43pvbljewtzx6zpsgpqh&e=1&st=o7z3akxe&dl=0">📄 CV</a> |
  <a href="mailto:d.sanchez.ordonez@psemail.eu">📧 Email</a> 
logo: /assets/profile.jpeg
theme: jekyll-theme-minimal
show_downloads: false
include:
  - assets/css
