title: "Daniel Sánchez Ordóñez"
description: >
  PhD Candidate, Paris School of Economics<br>
  <a href="/assets/cv.pdf">📄 CV</a> |
  <a href="mailto:d.sanchez.ordonez@psemail.eu">📧 Email</a> 
logo: /assets/profile.jpeg
theme: jekyll-theme-minimal
show_downloads: false
include:
  - assets/css
